FROM prom/prometheus:v2.54.1

COPY prometheus/prometheus.yml /etc/prometheus/prometheus.yml
COPY prometheus/alert_rules.yml /etc/prometheus/alert_rules.yml

RUN mkdir -p /tmp/prometheus

EXPOSE 9090

CMD ["--config.file=/etc/prometheus/prometheus.yml", \
     "--storage.tsdb.path=/tmp/prometheus", \
     "--storage.tsdb.retention.time=1d", \
     "--web.enable-lifecycle", \
     "--web.listen-address=0.0.0.0:9090"]
