FROM grafana/grafana:latest

# Copy Grafana provisioning configurations and dashboards into Grafana image
COPY grafana/provisioning /etc/grafana/provisioning
COPY grafana/dashboards /var/lib/grafana/dashboards

EXPOSE 3000
