apiVersion: v1
kind: Service
metadata:
  name: {{ include "pipeline-app.fullname" . }}
  labels:
    {{- include "pipeline-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.service.portName }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.portName }}
      protocol: TCP
  selector:
    {{- include "pipeline-app.selectorLabels" . | nindent 4 }}
